apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://skb-prometheus:9090
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://skb-loki:3100
    jsonData:
      maxLines: 1000
    editable: true
  
  - name: Jaeger
    type: jaeger 
    access: proxy
    url: http://skb-jaeger:16686
    editable: true